### ISSUE TITLE
Empty sections cause compiler warnings

### ISSUE THREAD

**Issue by wnortje** [mmontone/ten#3]
If there is an empty section which is not overridden, e.g. `{% section footer %}{% end %}` it causes a compiler warning like

```
In (TEN/COMPILER::RENDER-SECTION ((EQL 'TEN-TEMPLATES::FOOTER) TEN-TEMPLATES::BASE T)) inside an anonymous lambda form: Unused lexical variable TEN/TEMPLATE:%TEN-STREAM
```
Adding whitespace in the section removes the warning. `{% section footer %} {% end %}`

Empty sections should be possible without causing compiler warnings.

**Comment by mmontone** [comment]
Hi @wnortje, thanks for the report.

I cannot reproduce.

I've pushed a commit with such an empty section to one of the example templates: https://github.com/mmontone/ten/commit/a77db7995b8b9e777c19f474b49fffeb8def7e5e

But I see no compilation errors, and `(asdf:test-system :ten)` still all green.

Also, I do this: `(ten:compile-template (asdf:system-relative-pathname :ten "examples/inheritance.html"))` and see no warning or error.

Can you run the tests yourself and see what you get?

Question: that warning prevents the template from compiling successfully?

**Comment by wnortje** [comment]
HI

I ran the tests, all are green.

This warning does not prevent the template from compiling but it does clutter the build output.

I still get the warning. I am using CCL "Version 1.12-dev/v1.12-dev.1  (LinuxX8664)"

From a newly started REPL:
`(ql:quickload :ten.examples :verbose t)`

```
To load "ten.examples":
  Load 1 ASDF system:
    ten.examples
; Loading "ten.examples"
;Compiler warnings for "/home/wimpie/quicklisp/dists/quicklisp/software/ten-20210228-git/examples/inheritance.lisp" :
;   In (TEN/COMPILER::RENDER-SECTION ((EQL 'TEN/EXAMPLES::EMPTY) TEN/EXAMPLES:PARENT T)) inside an anonymous lambda form: Unused lexical variable TEN/TEMPLATE:%TEN-STREAM
```

**Comment by mmontone** [comment]
I've pushed a change. Let me know if the warning is still there.

**Comment by wnortje** [comment]
Thanks very much. The warnings are gone now.
